issuer: https://token.actions.githubusercontent.com

subject: repo:DataDog/datadog-aas-extension:ref:refs/heads/main

claim_pattern:
  event_name: schedule
  ref: refs/heads/main
  ref_protected: "true"
  job_workflow_ref: DataDog/datadog-aas-extension/\.github/workflows/java_extension_update_versions\.yml@refs/heads/main

permissions:
  contents: write
  pull_requests: write
