#!/usr/bin/env sh

main() {
    # Required to add the AAS metadata
    export DD_AZURE_APP_SERVICES=1

    CURRENT_DIR=$(pwd)
    echo "Set application directory as $CURRENT_DIR"

    echo "Setting Datadog environment variables"
    setEnvVars

    echo "Creating and switching to the Datadog directory at $DD_DIR"
    mkdir -p "$DD_DIR" && cd "$DD_DIR" || return

    case "$WEBSITE_STACK" in
        "NODE")
            setUpNodeEnv;;
        "DOTNETCORE")
            setUpDotnetEnv;;
        "PYTHON")
            setUpPyEnv;;
        "*")
            echo "Unsupported runtime. Exiting Datadog startup"
            return;;
    esac
    echo "Completed Datadog setup"
}

setEnvVars() {
    if [ -z "$DD_DIR" ]; then
        DD_DIR="/home/datadog"
    fi

    if [ -z "$DD_BINARIES_URL" ]; then
        DD_BINARIES_URL="https://github.com/DataDog/datadog-aas-extension/releases/download"
    fi

    if [ -z "$DD_AAS_LINUX_VERSION" ]; then
        DD_AAS_LINUX_VERSION="linux-v0.1.4-beta"
    fi

    if [ -z "$DD_TRACE_ENABLED" ]; then
        DD_TRACE_ENABLED="true"
    fi

    if [ -z "$DD_CUSTOM_METRICS_ENABLED" ]; then
        DD_CUSTOM_METRICS_ENABLED="false"
    fi
}

getBinaries() {
    if [ "$DD_TRACE_ENABLED" = "true" ]; then
        echo "Setting up the trace agent"
        setUpBinary "trace-agent"
    fi

    if [ "$DD_CUSTOM_METRICS_ENABLED" = "true" ]; then
        echo "Setting up DogStatsD"
        setUpBinary "dogstatsd"
    fi
}

setUpBinary() {
    # Binary is the name of the binary, trace-agent or dogstatsd
    # File is the expected archived file name of the binary

    BINARY="$1"
    FILE="$BINARY-${DD_AAS_LINUX_VERSION}.tar.gz"

    if [ ! -f "$FILE" ]; then

        if [ -f "$BINARY" ]; then
            echo "Removing old versions of $BINARY"
            rm "$BINARY*"
        fi

        echo "Downloading required Datadog binaries from $DD_BINARIES_URL/$DD_AAS_LINUX_VERSION/$FILE"
        if curl -L --fail "$DD_BINARIES_URL/$DD_AAS_LINUX_VERSION/$FILE" -o "$FILE"; then
            echo "Decompressing files"
            tar -zxf "$FILE" || return
        else
            echo "Failed to download the Datadog binary succesfully."
            return
        fi

    else
        echo "Version $DD_AAS_LINUX_VERSION of $BINARY previously installed"
    fi

    # Add start command for dogstatsd
    if [ "$BINARY" = "dogstatsd" ]; then BINARY="dogstatsd start"; fi

    echo "Starting $BINARY"
    ./"$BINARY" &
    BINARY_PID=$!
    trap 'kill $BINARY_PID ; exit' INT
}

setUpNodeEnv() {
    echo "Setting up Datadog tracing for Node"
    getBinaries || return
    echo "Installing Node tracer"
    yarn add dd-trace || return

    ORIG_NODE_OPTIONS=$NODE_OPTIONS
    export NODE_OPTIONS="--require=$DD_DIR/node_modules/dd-trace/init $ORIG_NODE_OPTIONS"

    # confirm updates to NODE_OPTIONS
    node --help >/dev/null || (export NODE_OPTIONS="$ORIG_NODE_OPTIONS" && return)
}

setUpDotnetEnv() {
    echo "Setting up Datadog tracing for .NET"
    getBinaries || return

    if [ -z "$DD_DOTNET_TRACER_VERSION" ]; then
        DD_DOTNET_TRACER_VERSION=2.19.0
    fi
    DD_DOTNET_TRACER_FILE=datadog-dotnet-apm-${DD_DOTNET_TRACER_VERSION}.tar.gz
    DD_DOTNET_TRACER_URL=https://github.com/DataDog/dd-trace-dotnet/releases/download/v${DD_DOTNET_TRACER_VERSION}/${DD_DOTNET_TRACER_FILE}

    echo "Installing .NET tracer from $DD_DOTNET_TRACER_URL"
    if curl -L --fail "$DD_DOTNET_TRACER_URL" -o "$DD_DOTNET_TRACER_FILE"; then
        tar -xzf "$DD_DOTNET_TRACER_FILE" || return
    else
        echo "Downloading the tracer was unsuccessful"
        return
    fi

    export CORECLR_ENABLE_PROFILING=1
    export CORECLR_PROFILER="{846F5F1C-F9AE-4B07-969E-05C26BC060D8}"
    export CORECLR_PROFILER_PATH="${DD_DIR}/Datadog.Trace.ClrProfiler.Native.so"
    export DD_DOTNET_TRACER_HOME="${DD_DIR}"
}

setUpPyEnv() {
    echo "Setting up Datadog tracing for Python"
    getBinaries || return

    if [ -z "$DD_PYTHON_TRACER_VERSION" ]; then
        DD_PYTHON_TRACER_VERSION=1.7.0
    fi

    pip install ddtrace
    # append ddtrace-run command to original start command
    DD_START_APP="ddtrace-run ${DD_START_APP}"
}

main
echo "Executing start command: \"$DD_START_APP\""
cd "$CURRENT_DIR"
eval "$DD_START_APP"
