#!/usr/bin/env sh

CURRENT_DIR=$(pwd)

# Required to add the AAS metadata 
export DD_AZURE_APP_SERVICES=1

if [ -z "$DD_DIR" ]; then
    DD_DIR="/home/datadog"
fi

if [ -z "$DD_BINARIES_URL" ]; then
    DD_BINARIES_URL="https://github.com/DataDog/datadog-aas-extension/releases/download"
fi

if [ -z "$DD_AAS_LINUX_VERSION" ]; then
    DD_AAS_LINUX_VERSION="linux-v0.1.3-beta"
fi

setUpCommonEnv() {
    echo "Creating Datadog directory"
    mkdir -p $DD_DIR && cd $DD_DIR || return

    FILE=trace-agent-${DD_AAS_LINUX_VERSION}.tar.gz

    if [ ! -f $FILE ]; then 

        if [ -f "trace-agent" ]; then 
            echo "Removing old versions of the trace agent"
            rm trace-agent* 
        fi

        echo "Downloading required Datadog binaries from $DD_BINARIES_URL/$DD_AAS_LINUX_VERSION/$FILE"
        curl_or_log_failure $DD_BINARIES_URL/$DD_AAS_LINUX_VERSION/$FILE $FILE
        
    else
        echo "Version $DD_AAS_LINUX_VERSION of the trace agent previously installed"
    fi
    
    curl_or_log_failure "https://gist.github.com/jcstorms1/4856d7be2ae390aa923275c3806be130/raw/ce688f7a7a1e42e5fc86c4e5c5626da68d6afa92/dogstatsd.gz" "dogstatsd.gz"
    gzip -d dogstatsd.gz
    
    echo "Starting trace agent"
    ./trace-agent &
    TRACER_PID=$!
    trap 'kill $TRACER_PID ; exit' INT

    echo "Starting Dogstatsd agent"
    ./dogstatsd start &
}

setUpNodeEnv() {
    echo "Setting up Datadog tracing for Node"
    setUpCommonEnv &
    setup_ID=$!
    
    echo "Installing Node tracer"
    yarn add dd-trace &
    yarn_ID=$!

    wait $setup_ID $yarn_ID
    ORIG_NODE_OPTIONS=$NODE_OPTIONS
    export NODE_OPTIONS="--require=$DD_DIR/node_modules/dd-trace/init $ORIG_NODE_OPTIONS"

    # confirm updates to NODE_OPTIONS
    node --help >/dev/null || (export NODE_OPTIONS=$ORIG_NODE_OPTIONS && return)
}

setUpDotnetEnv() {
    echo "Setting up Datadog tracing for .NET"

    setUpCommonEnv || return

    if [ -z "$DD_DOTNET_TRACER_VERSION" ]; then
        DD_DOTNET_TRACER_VERSION=2.19.0
    fi
    DD_DOTNET_TRACER_FILE=datadog-dotnet-apm-${DD_DOTNET_TRACER_VERSION}.tar.gz
    DD_DOTNET_TRACER_URL=https://github.com/DataDog/dd-trace-dotnet/releases/download/v${DD_DOTNET_TRACER_VERSION}/${DD_DOTNET_TRACER_FILE}

    echo "Installing .NET tracer from $DD_DOTNET_TRACER_URL"
    curl_or_log_failure $DD_DOTNET_TRACER_URL $DD_DOTNET_TRACER_FILE

    export CORECLR_ENABLE_PROFILING=1
    export CORECLR_PROFILER={846F5F1C-F9AE-4B07-969E-05C26BC060D8}
    export CORECLR_PROFILER_PATH=${DD_DIR}/Datadog.Trace.ClrProfiler.Native.so
    export DD_DOTNET_TRACER_HOME=${DD_DIR}
}

curl_or_log_failure() {
    if curl -L --fail "$1" -o "$2"; then echo
            echo "Decompressing files"
            tar -zxf "$2" || return
    else 
        echo "Failed to download the file succesfully from $1."
    fi
}

if [ "$WEBSITE_STACK" = "NODE" ]; then
    setUpNodeEnv;
elif [ "$WEBSITE_STACK" = "DOTNETCORE" ]; then
    setUpDotnetEnv;
fi

echo "Executing start command: \"$DD_START_APP\""
cd $CURRENT_DIR
eval "$DD_START_APP"
