name: Build Agent Process Manager

on: push

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up MSVC environment
      uses: microsoft/setup-msbuild@v2

    - name: Build 64 bit solution
      run: msbuild node/AgentProcessManager/AgentProcessManager.sln /p:Configuration=Release /p:Platform=x64

    - name: Build 32 bit solution
      run: msbuild node/AgentProcessManager/AgentProcessManager.sln /p:Configuration=Release /p:Platform=x86

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dlls
        path: |
          node/AgentProcessManager/x64/Release/AgentProcessManager.dll
          node/AgentProcessManager/Release/AgentProcessManager.dll
