name: Update Agent for Node Extension

on:
  workflow_dispatch:
    inputs:
      agent_version:
        description: "Agent version tag (0.0.0) to be used for a agent version bump."
        required: true
  repository_dispatch:
    types: [datadog-agent-release]

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Modify build-packages
        id: version
        run: |
          CURRENT_AGENT_VERSION=$(awk '/AGENT_VERSION=/{print}' node/scripts/build-packages.sh | awk -F '=' '{print $2}' | tr -d '"')

          AGENT_VERSION=${TEST_VERSION#v}

          echo "Current Agent Version: $CURRENT_AGENT_VERSION"
          echo "Updating to Agent Version: $AGENT_VERSION"

          sed -i -e "s/AGENT_VERSION=\"$CURRENT_AGENT_VERSION\"/AGENT_VERSION=\"$AGENT_VERSION\"/" node/scripts/build-packages.sh

          PR_BODY="Bumps the Agent version for the Node Extension to $AGENT_VERSION."

          echo "agent_version=$AGENT_VERSION" >> "$GITHUB_OUTPUT"
          echo "pr_body=$PR_BODY" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        id: pr
        uses: peter-evans/create-pull-request@v6.0.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "node-extension-agent-version-bump-${{steps.version.outputs.agent_version}}"
          commit-message: "[Node Agent Version Bump] Bump Agent to ${{steps.version.outputs.agent_version}}"
          delete-branch: true
          title: "[Node Agent Version Bump] Bump Agent to ${{steps.version.outputs.agent_version}}"
          body: "${{steps.version.outputs.pr_body}}"

      - name: Display output
        run: |
          echo "Pull Request Number - ${{ steps.pr.outputs.pull-request-number }}"
          echo "Pull Request URL - ${{ steps.pr.outputs.pull-request-url }}"
